version: "3"
name: web-app

services:
  develop:
    profiles: [develop]
    build:
      context: .
      target: develop
    volumes:
      - .:/web-app
      - /web-app/node_modules
    ports:
      - "80:5173"

  production:
    profiles: [production]
    build:
      context: .
      target: production
    ports:
      - "80:8080"
